[project]
name = "walmart-agentic-data-engineering"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "jiahern06", email = "jwon0198@student.monash.edu" }
]
requires-python = ">=3.11"
dependencies = [
    "airflow-operators>=0.11.0",
    "apache-airflow>=3.3.1",
    "databricks-sdk>=0.47.0",
    "dbt-core>=1.12.3",
    "dbt-databricks>=1.10.9",
]

[project.scripts]
walmart-agentic-data-engineering = "walmart_agentic_data_engineering:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
